# Generated by Django 4.0.6 on 2022-07-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='created_chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
