# Generated by Django 4.0.6 on 2022-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_chat_created_at_chatmember_member_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
