# Generated by Django 4.0.6 on 2022-07-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_chatmember_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
    ]
