# Generated by Django 4.0.6 on 2022-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_chatmember_chat_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
